const labels = {
    MUSICIAN_FIRST_CLASS: 'muzyk-i-klasa',
    LESSON_PLANS: 'plan-zajec',
    JOB_OFFERS: 'oferty-pracy',
    RECRUITMENT: 'rekrutacja',
    DELIVERING_ADDRESS: 'adres-do-doreczen',
    MUSICIAN_FIRST_CLASS_DOCUMENTS: 'muzyk-i-klasa-dokumenty',
    LEADERS: 'kierownicy-sekcji',
    DIRECTORS: 'dyrekcja',
    TEACHERS: 'pedagodzy',
    ADMINISTRATION: 'administracja',
    INSTRUMENTS: 'instrumenty',
    WHY_WORTH: 'dlaczego-warto',
    FREQUENT_QUESTIONS: 'czeste-pytania',
    TEACHING_METHODS: 'metody-nauczania',
    BUILDING: 'budowa-siedziby',
    DIPLOMAS: 'dyplomy',
    ARTICLES: 'artykuly',
    POSTERS: 'afisze',
    SCHOOL_DOCUMENTS: 'dokumenty-szkolne',
    LEADING_ORGAN: 'organ-prowadzacy',
    SUPERVISORY_ORGAN: 'organ-nadzorujacy',
    DATA_PROTECTION: 'ochrona-danych',
    ACCESSIBILITY_DECLARATION: 'deklaracja-dostepnosci',
    MUSICIAN_FIRST_CLASS_GALLERY: 'muzyk-i-klasa-galeria',
    TREASURY_OF_IDEAS: 'skarbnica-pomyslow',
    CREATIVITY_ZONE: 'strefa-tworczosci',
    CEA: 'cea',
    ELECTRONIC_DIARY: 'dziennik-elektroniczny',
    SCHOOL_STAFF: 'kadra-szkoly',
    SCHOOL: 'szkola',
    OUR_ACHIEVEMENTS: 'nasze-osiagniecia',
    EVENTS_ARCHIVE: 'archiwum-wydarzen',
    SCHOOL_REGULATIONS: 'przepisy-szkolne',
};

export default labels;
